name: 'igluctl'
description: 'Run igluctl with the provide arguments'
inputs:
  args:
    description: 'Arguments to pass to igluctl'
    required: true
    default: 'lint ./src/meltano/core/tracking/iglu-client-embedded/'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}
