FROM buildpack-deps:stretch

# @include ../vendor/python/Dockerfile

# @include ../vendor/node/Dockerfile

ENV melt_workdir /meltano
WORKDIR ${melt_workdir}

ENV PYTHONPATH ${melt_workdir}/packages

RUN pip install pip-tools uwsgi gevent

COPY packages/api/yarn.lock packages/api/
RUN cd packages/api && yarn

COPY requirements.txt ./
RUN pip install -r requirements.txt

CMD ['python']