# https://github.com/marketplace/actions/changelog-ci#user-content-configuration-file-options

changelog_type: pull_request  # or commit_message
header_prefix: ""
commit_changelog: true
comment_changelog: true
include_unlabeled_changes: true
pull_request_title_regex: '^Release'
version_regex: >  # example: '2.1.0 - (2022-06-17)'
  '?([0-9]{1,2})+[.]+([0-9]{1,2})+[.]+([0-9]{1,2})\s\-\s\(\d{1,2}-\d{1,2}-\d{4}\)'
group_config:
  # See ./.github/semantic.yml for semantic PR naming rules
  - title: New
    labels:
      - feat
  - title: Fixes
    labels:
      - fix
      - revert
  - title: Changes
    labels:
      - change
  - title: Breaks
    labels:
      - break
  - title: Improvements
    labels:
      - perf
  - title: Under the Hood
    labels:
      - style
      - refactor
  - title: "CI and Build Processes (TODO: Remove before release)"
    labels:
      - ci
      - build
      - test
      - chore
  - title: "Documentation Updates (TODO: Remove or trim before release)"
    labels:
      - docs

# Include for unlabeled for visibility. Section should be deleted before release.
unlabeled_group_title: 'Unlabeled Changes'
