
# Name your package! Package names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'meltano'
version: '1.0'

# This setting configures which "profile" dbt uses for this project. Profiles contain
# database connection information, and should be configured in the  ~/.dbt/profiles.yml file
profile: 'meltano'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that source models can be found
# in the "models/" directory. You probably won't need to change these!
source-paths: ["transform/models"]
analysis-paths: ["transform/analysis"]
test-paths: ["transform/tests"]
data-paths: ["tranfsorm/data"]
macro-paths: ["transform/macros"]

target-path: ".meltano/dbt/target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - ".meltano/dbt/target"
    - "dbt_modules"

# You can define configurations for models in the `source-paths` directory here.
# Using these configurations, you can enable or disable models, change how they
# are materialized, and more!

# In this example config, we tell dbt to build all models in the example/ directory
# as views (the default). Try changing `view` to `table` below, then re-running dbt
#
# SHOULD DISABLE ALL PER DEFAULT
models:
  meltano:
    tap-gitlab:
      vars:
        # these vars should either be injected at runtime
        schema: "gitlab"
