environments:
- name: prod
  config:
    plugins:
      extractors:
      - name: tap-slack-public
        config:
          thread_lookback_days: 7
      - name: tap-google-analytics
        config:
          start_date: '2022-02-20'
      - name: tap-gitlab
        config:
          groups: meltano
          start_date: '2020-01-01T00:00:00Z'
      - name: tap-github
        config:
          start_date: '2020-01-01'
      - name: tap-snowflake
        config:
          dbname: PROD
          user: MELTANO
          role: REPORTER
          warehouse: REPORTER
      - name: tap-snowflake-metrics-legacy
        config:
          tables: PROD.MELTANO_HUB.FACT_HUB_METRICS
      - name: tap-snowflake-metrics
        config:
          tables: PROD.MELTANO_HUB.FACT_VARIANT_HUB_METRICS
      - name: tap-snowflake-audit
        config:
          tables: PROD.MELTANO_HUB.HUB_METRICS_AUDIT
      - name: tap-snowflake-singer-activity
        config:
          tables: PROD.SLACK_NOTIFICATIONS.SLACK_ALERTS
      loaders:
      - name: target-snowflake
        config:
          dbname: RAW
          user: MELTANO
          role: LOADER
          warehouse: LOADER
          default_target_schema: ${MELTANO_EXTRACT__LOAD_SCHEMA}
      - name: target-apprise
        config:
          stream_maps:
            PROD-SLACK_NOTIFICATIONS-SLACK_ALERTS:
              TITLE: null
              title: TITLE
              BODY: null
              body: BODY
      utilities:
      - name: dbt-snowflake
        config:
          user: MELTANO
          role: TRANSFORMER
          warehouse: TRANSFORMER
          database: PROD
      - name: sqlfluff
        config:
          user: MELTANO
      - name: great_expectations
        config:
          prod_database: PROD
          raw_database: RAW
          username: MELTANO
          role: TRANSFORMER
          warehouse: TRANSFORMER
  env:
    HUB_METRICS_S3_PATH: s3://prod-meltano-bucket-01/hub_metrics/
    PERMISSION_BOT_USER: permission_bot
    PERMISSION_BOT_WAREHOUSE: ADMIN
    PERMISSION_BOT_DATABASE: SNOWFLAKE_SAMPLE_DATA
    PERMISSION_BOT_ROLE: SECURITYADMIN
