#cloud-config
groups:
  - meltano

users:
  - name: meltano
    system: true
    homedir: /var/meltano
    no_user_group: true
    primary_group: meltano

write_files:
  - path: /etc/caddy/environment
    content: |
      HOSTNAME=$HOSTNAME.meltanodata.com
