version: '3.1'
services:
  meltano:
    image: meltano/meltano
    working_dir: /project
    volumes:
    - ./:/project
    ports:
    - '5000:5000'
    - '5010:5010'
  warehouse_db:
    image: postgres:11
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_PASSWORD: warehouse
      POSTGRES_USER: warehouse
    ports:
    - '5502:5432'
