#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Meltano installed at '/var/meltano/.venv/bin/meltano'

You can source this virtual environment to have simple access to the Meltano cli

'source /var/meltano/.venv/bin/activate'

The 'meltano' command is now available.

********************************************************************************
EOF
