netsuite_accounts:
    constraints: 
        not_null: 
        - internal_account_id
        - account_name
        - account_type
        unique:
        - internal_account_id
        - account_name

netsuite_applications:
    constraints:
        not_null:
        - application_id
        - transaction_id
        - transaction_line
        - application_amount
        - doc_id
        - application_type
        unique:
        - application_id


netsuite_currencies:
    constraints: 
        not_null: 
        - currency_id
        - currency_name
        - currency_symbol
        - exchange_rate
        unique:
        - currency_id
        - currency_name
        - currency_symbol

netsuite_customers:
    constraints: 
        not_null: 
        - customer_id
        - entity_name
        unique:
        - customer_id
        - entity_name

netsuite_departments:
    constraints:
        not_null:
        - department_id
        - department_name
        unique:
        - department_id

netsuite_expenses:
    constraints:
        not_null:
        - expense_id
        - transaction_id
        - transaction_line
        - account_id
        - account_name
        unique: 
        - expense_id

netsuite_subsidiaries:
    constraints: 
        not_null: 
        - subsidiary_id
        - subsidiary_name
        - currency
        - country
        unique:
        - subsidiary_id
        - subsidiary_name

netsuite_transaction_items:
    constraints:
        not_null:
        - transaction_item_id
        - transaction_id
        - transaction_line
        - item_id
        - item_name
        unique:
        - transaction_item_id

netsuite_transaction_lines:
    constraints: 
        not_null: 
        - transaction_line_id
        - transaction_id
        - transaction_line
        - account_id
        - account_name
        unique:
        - transaction_line_id

netsuite_transactions:
    constraints:
        not_null:
        - transaction_id
        - transaction_date
        unique:
        - transaction_id

netsuite_vendors:
    constraints: 
        not_null: 
        - internal_vendor_id
        - entity_name
        unique:
        - internal_vendor_id
        - entity_name


