version: 1
default_environment: dev
project_id: abd310b5-698b-4244-a109-9490047fa2ec
send_anonymous_usage_stats: false
annotations:
  example-annotation:
    a_key: a value
  another-annotation-category:
    best_season: Autumn
    the_purpose_of_this_annotation: Nothing much
plugins:
  extractors:
  - name: tap-gitlab
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-gitlab.git
    config:
      projects: meltano/meltano
    select:
    - commits.*
  loaders:
  - name: target-jsonl
    variant: andyh1203
    pip_url: target-jsonl
environments:
- name: dev
jobs:
- name: gitlab-to-jsonl
  tasks:
  - tap-gitlab target-jsonl
schedules:
- name: daily-gitlab-to-jsonl
  interval: 5 4 * * *
  job: gitlab-to-jsonl
