sfdc_sales_accepted_opportunity:
    constraints:
        not_null:
            - opportunity_segment
            - opportunity_name

users:
    constraints:
        unique:
            - id

sfdc_accounts_xf:
    constraints:
        not_null:
            - account_id
            - account_name
        unique:
            - account_id