{{- if .Values.global.ingress.enabled -}}
{{- $fullName := include "oauth2-proxy.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "oauth2-proxy.name" . }}
    chart: {{ template "oauth2-proxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.provider: nginx
    {{- with .Values.global.ingress.annotations }}
    {{ toYaml . | indent 4 }}
    {{- end }}
spec:
{{- if .Values.global.ingress.tls }}
  tls:
  {{- range .Values.global.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.global.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
        - backend:
            serviceName: {{ $fullName }}
            servicePort: 4180
          path: /oauth2
  {{- end }}
{{- end }}
