apiVersion: v1
kind: Service
metadata:
  name: {{ template "oauth2-proxy.fullname" . }}
  labels:
    app: {{ template "oauth2-proxy.name" . }}
    chart: {{ template "oauth2-proxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    app: {{ template "oauth2-proxy.name" . }}
    release: {{ .Release.Name }}