{{- if .Values.global.ingress.enabled -}}
{{- $fullName := include "meltano.fullname" . -}}
{{- $ingressPath := .Values.global.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "meltano.name" . }}
    chart: {{ template "meltano.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.provider: nginx
    {{- if index .Values "global" "oauth2-proxy" "enabled" }}
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    # Requires 0.18.0 which is't out yet
    # nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$request_uri"
    {{- end }}
    {{- with .Values.global.ingress.annotations }}
    {{ toYaml . | indent 4 }}
    {{- end }}
spec:
{{- if .Values.global.ingress.tls }}
  tls:
  {{- range .Values.global.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.global.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
  {{- end }}
{{- end }}
