version: 1
disable_existing_loggers: false

formatters:
  default:
    format: "[%(asctime)s] [%(process)d|%(threadName)10s|%(name)s] [%(levelname)s] %(message)s"
  structured_plain:
    (): meltano.core.logging.console_log_formatter
    colors: False
  structured_colored:
    (): meltano.core.logging.console_log_formatter
    colors: True
  key_value:
    (): meltano.core.logging.key_value_formatter
    sort_keys: False
  json:
    (): meltano.core.logging.json_formatter

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: structured_plain
    stream: "ext://sys.stderr"
  jsonl_file:
    class: logging.FileHandler
    level: DEBUG
    filename: integration-test.log.jsonl
    formatter: json
  plain_file:
    class: logging.FileHandler
    level: DEBUG
    filename: integration-test.log
    formatter: structured_plain

root:
  level: DEBUG
  propagate: yes
  handlers: [console, jsonl_file, plain_file]
