name: 'build-scan-push'
description: 'Build a Docker image, scan it, then push it to Docker Hub'

inputs:
  tags:
    description: 'The Docker tags for the image that will be built'
    required: true
  build-args:
    description: 'The Docker build args'
    required: true
  push:
    description: 'Whether to push the built image to Docker Hub'
    required: true
  dockerhub-username:
    description: 'The Docker Hub username to use when pushing the image'
    required: true
  dockerhub-password:
    description: 'The Docker Hub password to use when pushing the image'
    required: true

runs:
  using: 'composite'
  steps:
    # Per: https://github.com/marketplace/actions/build-and-push-docker-images
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the image
      uses: docker/build-push-action@v3
      with:
        load: true
        context: "{{defaultContext}}:docker/publish"
        tags: ${{ inputs.tags }}
        build-args: ${{ inputs.build-args }}

    - name: Get the ID of the image
      id: get-image-id
      shell: bash
      run: echo "::set-output name=id::$(docker images -q meltano/meltano | head -n 1)"

    # - name: Scan the image with 'Azure/container-scan'
    #   uses: Azure/container-scan@v0
    #   with:
    #     image-name: ${{ steps.get-image-id.outputs.id }}
    #     run-quality-checks: true
    #     severity-threshold: MEDIUM

    - name: Scan the image with 'anchore/scan-action'
      id: anchore-scan
      uses: anchore/scan-action@v3
      with:
        image: ${{ steps.get-image-id.outputs.id }}
        acs-report-enable: true
        fail-build: false

    - name: Upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.anchore-scan.outputs.sarif }}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-password }}

    # - name: Push the scanned image to Docker Hub
    #   if: ${{ inputs.push == 'true' }}
    #   shell: bash
    #   run: docker image push --all-tags meltano/meltano

    - name: Delete the image
      shell: bash
      run: docker image rm --force ${{ steps.get-image-id.outputs.id }}
