[project]
name = "meltano-state-backend-s3"
version = "0.1.0"
description = "AWS S3 state backend for Meltano"
readme = "README.md"
authors = [{ name = "Meltano", email = "hello@meltano.com" }]
requires-python = ">=3.10"
dependencies = [
  "boto3>=1.35,<2",
]

[dependency-groups]
dev = [
  { include-group = "typing" },
]
typing = [
  "boto3-stubs[essential]>=1.35",
]

[project.entry-points."meltano.settings"]
s3_aws_access_key_id = "meltano_state_backend_s3:AWS_ACCESS_KEY_ID"
s3_aws_secret_access_key = "meltano_state_backend_s3:AWS_SECRET_ACCESS_KEY"
s3_endpoint_url = "meltano_state_backend_s3:ENDPOINT_URL"

[project.entry-points."meltano.state_backends"]
s3 = "meltano_state_backend_s3:S3StateStoreManager"

[build-system]
requires = ["uv_build>=0.8.14,<0.9.0"]
build-backend = "uv_build"
