[project]
name = "meltano-state-backend-gcs"
version = "0.1.0"
description = "Google Cloud Storage state backend for Meltano"
readme = "README.md"
authors = [{ name = "Meltano", email = "hello@meltano.com" }]
requires-python = ">=3.10"
dependencies = ["google-cloud-storage>=1.31.0"]

[project.entry-points."meltano.settings"]
google_application_credentials = "meltano_state_backend_gcs:APPLICATION_CREDENTIALS"  # Deprecated! Remove in Meltano v4
google_application_credentials_path = "meltano_state_backend_gcs:APPLICATION_CREDENTIALS_PATH"
google_application_credentials_json = "meltano_state_backend_gcs:APPLICATION_CREDENTIALS_JSON"

[project.entry-points."meltano.state_backends"]
# These keys should match the expected scheme for URIs of
# the given type. E.g., filesystem state backends have a
# file://<path>/<to>/<state directory> URI
gs = "meltano_state_backend_gcs:GCSStateStoreManager"

[build-system]
requires = ["uv_build>=0.8.14,<0.9.0"]
build-backend = "uv_build"
