name: Auto Assign to Project(s)

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to Product Roadmap Project
    steps:
    - name: Assign NEW issues and NEW pull requests to Product Roadmap
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/orgs/meltano/projects/4/'
