name: Auto Assign to Project(s)

on:
  issues:
    types: [opened]

jobs:
  assign_one_project:
    name: Assign to Product Roadmap Project
    runs-on: ubuntu-latest
    steps:
    - name: Assign NEW issues to Product Roadmap
      uses: actions/add-to-project@main
      with:
        project-url: 'https://github.com/orgs/meltano/projects/4'
        github-token: ${{ secrets.MELTYBOT_GITHUB_PROJECT_AUTH_TOKEN }}
