name: Lint integration test shell scripts

on:
  pull_request:
    paths:
      - 'integration/**'
  workflow_dispatch:
    inputs: {}

jobs:
  shell_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.0.2

      - name: Integration test shell lint
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_names: mdsh
          scandir: './integration'
          check_together: 'yes'
