name: Create release draft

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version Number"
        type: string
        required: true
        default: 2.0.0
      force:
        description: "Force Push (ignore validation)"
        type: boolean
        required: true
        default: false

jobs:
  draft_release:

    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    permissions:
      contents: write       # to create a github release
      pull-requests: write  # to create and update PRs

    steps:
    - uses: actions/checkout@v2

    - name: Validate version input
      if: ${{ github.event.inputs.force != true }}
      id: validate-version
      uses: ./.github/actions/validate-version-sequence
      with:
        version-proposed: ${{ github.event.inputs.version }}
    - name: Debug version bump type
      run: echo "${{ steps.validate-version.outputs.bump-type }}"

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        # Version of Poetry to use
        version: 1.1.13
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Set up Python
      uses: actions/setup-python@v4.0.0
      with:
        # https://github.com/actions/setup-python
        python-version: 3.9
        architecture: x64
        cache: 'poetry'
    - name: Poetry install
      run: |
        poetry install

    - name: Bump version
      run: |
        BUMP_TYPE="${{ steps.validate-version.outputs.bump-type }}"
        echo "Flushing changelog entries with '--$BUMP_TYPE' flag..."
        poetry run changelog release --$BUMP_TYPE --yes
        echo "Adding changelog to git..."
        git add CHANGELOG.md
        echo "Bumping version entries..."
        poetry run bumpversion "$BUMP_TYPE" --new-version="$NEW_VER" --allow-dirty --no-commit --no-tag

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      id: create-pull-request
      with:
        # https://github.com/peter-evans/create-pull-request
        commit-message: version bump (auto)
        title: Release v${{ github.event.inputs.version }}
        body: |
          Bump changelog for release v${{ github.event.inputs.version }}
        branch: release/v${{ github.event.inputs.version }}
        base: main
        labels: release

    - name: Create release draft
      # # Can't be run from forks:
      # if: ${{ github.event.repository.name == 'meltano/meltano' }}
      uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # https://github.com/release-drafter/release-drafter
        version: ${{ github.event.inputs.version }}
        commitish: release/v${{ github.event.inputs.version }}

    - name: Approve Pull Request
      if: ${{ steps.create-pull-request.outputs.pull-request-number != 0 }}
      uses: juliangruber/approve-pull-request-action@v1.1.1
      with:
        # https://github.com/juliangruber/approve-pull-request-action
        github-token: ${{ secrets.ACTIONS_BOT_TOKEN }}
        number: ${{ steps.create-pull-request.outputs.pull-request-number }}
