name: GitHub Actions Security Analysis with zizmor 🌈

on:
  push:
    branches:
      - main
      - 'v*'
  pull_request:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  zizmor:
    name: Zizmor Security Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write # create security reports for the repo
      contents: read # read the contents of the repo
      actions: read # read the actions of the repo
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0

      - name: Run zizmor 🌈
        run: >
          uvx zizmor
          --min-severity=informational
          --persona=pedantic
          --format=sarif
          .github > results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@0d579ffd059c29b07949a3cce3983f0780820c98 # v4.32.6
        with:
          sarif_file: results.sarif
          category: zizmor
