name: GitHub Actions Security Analysis with zizmor 🌈

on:
  push:
    branches:
      - main
      - 'v*'
  pull_request:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  zizmor:
    name: Zizmor Security Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write # create security reports for the repo
      contents: read # read the contents of the repo
      actions: read # read the actions of the repo
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa # v0.5.7
        with:
          persona: pedantic
