name: GitHub Actions Security Analysis with zizmor 🌈

on:
  push:
    branches:
      - main
      - 'v*'
  pull_request:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  zizmor:
    name: Zizmor Security Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write # create security reports for the repo
      contents: read # read the contents of the repo
      actions: read # read the actions of the repo
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@70fb788f84895a7701f5643d103d587e460b5c99 # v0.6.3
        with:
          persona: pedantic
