digitalocean_marketplace:
  extends: .only:version-tags
  image:
    name: hashicorp/packer
    entrypoint: [""]
  stage: distribute
  script:
    - cd cloud/packer
    - packer build marketplace-image.json
