.docker_build:
  image: docker:latest
  variables:
    DOCKERFILE: .
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  before_script:
    - source .gitlab/ci/scripts/docker_build_before_script.sh
  script:
    - source .gitlab/ci/scripts/docker_build_script.sh
