.build_prod:
  extends:
  - .docker_build
  - .parallel:python_version
  stage: build-meltano
  needs:
    - job: meltano_base
      optional: true
    - job: meltano_base_forks
      optional: true
  variables:
    DOCKERFILE: docker/prod/Dockerfile
    IMAGE_NAME: $CI_REGISTRY_IMAGE
  before_script:
    - source .gitlab/ci/scripts/docker_build_before_script.sh
    - source .gitlab/ci/scripts/python_image_version.sh
    - export EXTRA_ARGS="--build-arg BASE_IMAGE=$CI_REGISTRY_IMAGE/base:$BASE_SHA-python$PYTHON_IMAGE_VERSION"
    - export IMAGE_TAG=$CI_COMMIT_SHA-python$PYTHON_IMAGE_VERSION
  artifacts:
    paths:
      - dist

# Manages:
#  - meltano/meltano:<sha>-python<version>
meltano_dev:
  extends: .build_prod
  only:
    - branches@meltano/meltano
  except:
    - master

# Manages:
#  - <fork namespace>/meltano:<sha>-python<version>
meltano_dev_forks:
  extends: .build_prod
  except:
    - branches@meltano/meltano
    - tags@meltano/meltano

# Manages:
#  - meltano/meltano:<sha>-python<version>
#  - meltano/meltano:edge-python<version>
#  - meltano/meltano:edge
meltano_edge_images:
  extends:
    - .build_prod
    - .only:master
  script:
    - source .gitlab/ci/scripts/docker_build_script.sh
    - docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:edge-python$PYTHON_IMAGE_VERSION
    - docker push $IMAGE_NAME:edge-python$PYTHON_IMAGE_VERSION

    - '[[ "$PYTHON_VERSION" == "3.6" ]] && docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:edge || true'
    - '[[ "$PYTHON_VERSION" == "3.6" ]] && docker push $IMAGE_NAME:edge || true'
