docker_licnese_finder:
  stage: build-meltano
  image: "docker:latest"
  services:
    - "docker:dind"
  before_script:
    - docker --version
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build . -f license_finder/Dockerfile -t $CI_REGISTRY_IMAGE/license_finder:latest
    - docker push $CI_REGISTRY_IMAGE/license_finder:latest
